name = "brainafk"
compatibility_date = "2023-09-04"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "public"

[build]
command = "npm run build"
output_dir = "build/client"

[build.environment]
NODE_VERSION = "18"

[dev]
port = 8788
